
spring.application.name=school
spring.datasource.url= jdbc:postgresql://localhost:5432/hogwarts
spring.datasource.username= student
spring.datasource.password= chocolatefrog
# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto= validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
path.to.avatars.folder= /Users/Papa/Documents/avatars
spring.liquibase.change-log=classpath:liquibase/changelog-master.yml
Logging.level.ru.hogwarts.school.service=debug
server.port=8080
